default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: kids_village_development

test:
  <<: *default
  database: kids_village_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
